---
- name: Install and start Jenkins on CentOS using shell commands
  hosts: all
  become: true
  tasks:
    - name: Install wget 
      package:
        name: wget
        state: present

    - name: Install Jenkins using shell commands
      shell: |
        set -e  # Exit immediately on any error
        # Download Jenkins repository configuration
        wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
        # Import Jenkins GPG key
        rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        # Update system packages
        yum upgrade -y
        # Install dependencies and Jenkins
        yum install -y fontconfig java-21-openjdk jenkins
        # Reload systemd daemon
        systemctl daemon-reload
      args:
        executable: /bin/bash

    - name: Start and enable Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: yes
        daemon_reload: yes


#COMMAND
---
- name: command
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Check system uptime
      ansible.builtin.command: uptime
      register: uptime_result
    - name: Display uptime
      debug:
         var: uptime_result.stdout

#COMMAND
---
- name: command
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: list out items
      ansible.builtin.command: ls -la
      register: output
    - name: Display output
      debug:
         var: output



#COMMAND
---
- name: command
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: list out items
      ansible.builtin.command: ls -la
      register: output
    - name: Display output
      debug:
         msg: "{{output}}"